openapi: 3.1.0
info:
  title: Blockchain API
  description: APIs for retrieving Bitcoin-related information from Blockchain.info
  version: 1.0.0
servers:
  - url: https://blockchain.info
    description: Blockchain.info API server
paths:
  /unconfirmed-transactions:
    get:
      summary: Get unconfirmed Bitcoin transactions
      operationId: getUnconfirmedTransactions
      responses:
        '200':
          description: A list of unconfirmed Bitcoin transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  txs:
                    type: array
                    items:
                      type: object
                      properties:
                        hash:
                          type: string
                          description: The hash of the transaction
                        ver:
                          type: integer
                          description: The transaction version
                        vin_sz:
                          type: integer
                          description: The number of inputs in the transaction
                        vout_sz:
                          type: integer
                          description: The number of outputs in the transaction
                        size:
                          type: integer
                          description: The size of the transaction in bytes
                        weight:
                          type: integer
                          description: The weight of the transaction
                        fee:
                          type: integer
                          description: The transaction fee
                        relayed_by:
                          type: string
                          description: The IP address of the node that relayed the transaction
                        lock_time:
                          type: integer
                          description: The transaction lock time
                        tx_index:
                          type: integer
                          description: The transaction index
                        double_spend:
                          type: boolean
                          description: Indicates if the transaction is a double spend
                        time:
                          type: integer
                          description: The time of the transaction
                        block_index:
                          type: integer
                          description: The index of the block containing the transaction
                        block_height:
                          type: integer
                          description: The height of the block containing the transaction
                        inputs:
                          type: array
                          items:
                            type: object
                            properties:
                              sequence:
                                type: integer
                                description: The input sequence number
                              witness:
                                type: string
                                description: The input witness
                              script:
                                type: string
                                description: The input script
                              index:
                                type: integer
                                description: The index of the input
                              prev_out:
                                type: object
                                properties:
                                  addr:
                                    type: string
                                    description: The address of the previous output
                                  n:
                                    type: integer
                                    description: The index of the previous output
                                  script:
                                    type: string
                                    description: The previous output script
                                  spending_outpoints:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        n:
                                          type: integer
                                          description: The index of the spending outpoint
                                        tx_index:
                                          type: integer
                                          description: The index of the spending transaction
                                  spent:
                                    type: boolean
                                    description: Indicates if the previous output is spent
                                  tx_index:
                                    type: integer
                                    description: The index of the transaction
                                  type:
                                    type: integer
                                    description: The type of the previous output
                                  value:
                                    type: integer
                                    description: The value of the previous output
                        out:
                          type: array
                          items:
                            type: object
                            properties:
                              type:
                                type: integer
                                description: The type of the output
                              spent:
                                type: boolean
                                description: Indicates if the output is spent
                              value:
                                type: integer
                                description: The value of the output
                              spending_outpoints:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    n:
                                      type: integer
                                      description: The index of the spending outpoint
                                    tx_index:
                                      type: integer
                                      description: The index of the spending transaction
                              n:
                                type: integer
                                description: The index of the output
                              tx_index:
                                type: integer
                                description: The index of the transaction
                              script:
                                type: string
                                description: The output script
                              addr:
                                type: string
                                description: The address associated with the output
                        rbf:
                          type: boolean
                          description: Indicates if the transaction has opt-in replace-by-fee enabled

  /unspent:
    get:
      summary: Get unspent outputs for a Bitcoin address
      operationId: getUnspentOutputs
      parameters:
        - name: active
          in: query
          description: Bitcoin address (base58 or xpub)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of unspent outputs for the given address
          content:
            application/json:
              schema:
                type: object
                properties:
                  unspent_outputs:
                    type: array
                    items:
                      type: object
                      properties:
                        tx_hash_big_endian:
                          type: string
                          description: The transaction hash in big endian format
                        tx_hash:
                          type: string
                          description: The transaction hash
                        tx_output_n:
                          type: integer
                          description: The index of the output in the transaction
                        script:
                          type: string
                          description: The output script
                        value:
                          type: integer
                          description: The value of the output in satoshis
                        value_hex:
                          type: string
                          description: The hexadecimal value of the output
                        confirmations:
                          type: integer
                          description: The number of confirmations
                        tx_index:
                          type: integer
                          description: The transaction index
components:
  schemas:
    miningpool:
      type: object
      properties:
        pools:
          type: array
          items:
            $ref: "#/components/schemas/pool"
        blockCount:
          type: integer
          description: Total number of blocks mined in the last 24 hours
        lastEstimatedHashrate:
          type: number
          description: Last estimated hashrate

    pool:
      type: object
      properties:
        poolId:
          type: integer
          description: The unique ID of the pool
        name:
          type: string
          description: The name of the mining pool
        link:
          type: string
          format: uri
          description: The URL of the mining pool's website
        blockCount:
          type: integer
          description: Number of blocks mined by the pool in the last 24 hours
        rank:
          type: integer
          description: The ranking of the pool based on blocks mined in the last 24 hours
        emptyBlocks:
          type: integer
          description: Number of empty blocks mined by the pool in the last 24 hours
        slug:
          type: string
          description: A unique identifier for the pool
        avgMatchRate:
          type: number
          description: Average match rate of the pool's blocks in the last 24 hours
        avgFeeDelta:
          type: string
          description: Average fee delta of the pool's blocks in the last 24 hours
        poolUniqueId:
          type: integer
          description: The unique ID of the pool

    countryNode
